"""add_coverage_report

Revision ID: 2525dc03828b
Revises: e3e4bb2ec5fb
Create Date: 2026-04-24 14:00:43.522525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2525dc03828b'
down_revision: Union[str, None] = 'e3e4bb2ec5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_usage_user_id', table_name='token_usage')
    op.drop_table('token_usage')
    op.add_column('agent_sessions', sa.Column('coverage_report', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_sessions', 'coverage_report')
    op.create_table('token_usage',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='token_usage_pkey')
    )
    op.create_index('ix_token_usage_user_id', 'token_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###
