"""subscription_credits

Revision ID: 6cc7569a33cd
Revises: 4d5acaaccec8
Create Date: 2026-04-23 10:30:07.044722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cc7569a33cd'
down_revision: Union[str, None] = '4d5acaaccec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_usage_user_id', table_name='token_usage')
    op.drop_table('token_usage')
    op.add_column('users', sa.Column('chat_status', sa.String(), server_default='none', nullable=False))
    op.add_column('users', sa.Column('credits', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credits')
    op.drop_column('users', 'chat_status')
    op.create_table('token_usage',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='token_usage_pkey')
    )
    op.create_index('ix_token_usage_user_id', 'token_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###
